### ISSUE TITLE
Pages don't load properly

### ISSUE THREAD

**Issue by Hiieu** [OpenTechSchool/js-beginners-day1#39]
I got this when open link on any pages"

![untitled](https://f.cloud.github.com/assets/6671375/2169638/a45d0864-955d-11e3-8f3e-ba248cf01339.PNG)

**Comment by theophani** [comment]
It sounds like you are opening these files from a copy on your computer when you see this. If so, than what you are seeing is normal, and you have to manually click “index.html”. The way to get it to work as you expect is to serve these pages from a web server running on your computer instead, for example, using Apache. But really, you can just click index.html.
