### ISSUE TITLE
Proposal: clarification & small tweaks

### ISSUE THREAD

**Issue by autarc** [OpenTechSchool/js-beginners-day1#4]
Perhaps in the cheat sheet could the including type comparision '===' be added to the operators.

Since it's not trivial, it could be irritating if people start to take a look at public code and see more than the mentioned options. Knowing about the difference could also prevent missunderstandings in the future.

For people who come from a different developer background, it would perhaps be good to know that you can use multi lines comments /\* */ as well (e.g. for an explanation of a function instead of an inline hint for a variable).

And for convenience: the Chrome Dev Tools can be opened with just one key (F12) - same goes for Firebug/IE9+.

**Comment by theophani** [comment]
This workshop is aimed at absolute beginner programmers i.e. people with no development background.

Our plan is not to teach JavaScript, but to teach programming using JavaScript.

The details you talk about do not fit into the narrative of introducing concepts of programming, but are details about JavaScript syntax. We are trying not to overwhelm the beginner with options. You seem to want to be trying to them to be good open source contributors :)

**Comment by marijnh** [comment]
Agreed. I left out `===` and `!==` entirely for the simple reason that it's another concept to bother people with, which, for the kind of minimal stuff we'll be doing in these workshops, they don't really need yet.
