### ISSUE TITLE
Finish the German translation

### ISSUE THREAD

**Issue by marijnh** [OpenTechSchool/js-beginners-day1#8]
Someone, please. We've only got three more days.

**Comment by theophani** [comment]
Pretty sure Fronx is on it :)

## 

+49 176 32578373
Mobile email. Sorry if short. Auto-correction apologies.

**Comment by fronx** [comment]
Oh, erm, ya, will do! \o/

**Comment by marijnh** [comment]
Wunderbar.

**Comment by knuton** [comment]
Fronx, do you need any help still with translating page 3 and 4?

**Comment by fronx** [comment]
@knuton Sure, go ahead and translate away if you want. Much appreciated.

**Comment by knuton** [comment]
@fronx OK, I will have some time this afternoon, from 2pm or so. Please push if you have translated more of the material by then.

**Comment by knuton** [comment]
@xMartin is doing page 4, so if anyone feels like translating, help with day 2.

**Comment by sdepold** [comment]
This is done right?
